using System.ComponentModel;

namespace Core.Core
{
    [Description("KeyName")]
    public enum KeyName
    {
        [Description("Escape")]
        Escape,
        [Description("D1")]
        D1,
        [Description("D2")]
        D2,
        [Description("D3")]
        D3,
        [Description("D4")]
        D4,
        [Description("D5")]
        D5,
        [Description("D6")]
        D6,
        [Description("D7")]
        D7,
        [Description("D8")]
        D8,
        [Description("D9")]
        D9,
        [Description("D0")]
        D0,
        [Description("Minus")]
        Minus,
        [Description("Equals")]
        Equals,
        [Description("Plus")]
        Plus,
        [Description("BackSpace")]
        BackSpace,
        [Description("Tab")]
        Tab,
        [Description("Q")]
        Q,
        [Description("W")]
        W,
        [Description("E")]
        E,
        [Description("R")]
        R,
        [Description("T")]
        T,
        [Description("Y")]
        Y,
        [Description("U")]
        U,
        [Description("I")]
        I,
        [Description("O")]
        O,
        [Description("P")]
        P,
        [Description("LeftBracket")]
        Lbracket,
        [Description("RightBracket")]
        Rbracket,
        [Description("Enter")]
        Enter,
        [Description("LeftControl")]
        LControl,
        [Description("A")]
        A,
        [Description("S")]
        S,
        [Description("D")]
        D,
        [Description("F")]
        F,
        [Description("G")]
        G,
        [Description("H")]
        H,
        [Description("J")]
        J,
        [Description("K")]
        K,
        [Description("L")]
        L,
        [Description("Semicolon")]
        Semicolon,
        [Description("Apostrophe")]
        Apostrophe,
        [Description("Tilde")]
        Tilde,
        [Description("LeftShift")]
        LShift,
        [Description("Backslash")]
        Backslash,
        [Description("Z")]
        Z,
        [Description("X")]
        X,
        [Description("C")]
        C,
        [Description("V")]
        V,
        [Description("B")]
        B,
        [Description("N")]
        N,
        [Description("M")]
        M,
        [Description("Comma")]
        Comma,
        [Description("Dot")]
        Dot,
        [Description("Slash")]
        Slash,
        [Description("RightShift")]
        RShift,
        [Description("Multiply")]
        Multiply,
        [Description("LeftAlt")]
        LAlt,
        [Description("Space")]
        Space,
        [Description("CapsLock")]
        CapsLock,
        [Description("F1")]
        F1,
        [Description("F2")]
        F2,
        [Description("F3")]
        F3,
        [Description("F4")]
        F4,
        [Description("F5")]
        F5,
        [Description("F6")]
        F6,
        [Description("F7")]
        F7,
        [Description("F8")]
        F8,
        [Description("F9")]
        F9,
        [Description("F10")]
        F10,
        [Description("F11")]
        F11,
        [Description("F12")]
        F12,
        [Description("F13")]
        F13,
        [Description("F14")]
        F14,
        [Description("F15")]
        F15,
        [Description("NumLock")]
        NumLock,
        [Description("ScrollLock")]
        ScrollLock,
        [Description("NumPad7")]
        NumPad7,
        [Description("NumPad8")]
        NumPad8,
        [Description("NumPad9")]
        NumPad9,
        [Description("NumPadMinus")]
        NumPadMinus,
        [Description("NumPad4")]
        NumPad4,
        [Description("NumPad5")]
        NumPad5,
        [Description("NumPad6")]
        NumPad6,
        [Description("NumPadPlus")]
        NumPadPlus,
        [Description("NumPad1")]
        NumPad1,
        [Description("NumPad2")]
        NumPad2,
        [Description("NumPad3")]
        NumPad3,
        [Description("NumPad0")]
        NumPad0,
        [Description("NumPadDecimal")]
        NumPadDecimal,
        [Description("NumPadEnter")]
        NumPadEnter,
        [Description("RightControl")]
        RControl,
        [Description("NumPadDivide")]
        NumPadDivide,
        [Description("PrintScreen")]
        PrintScreen,
        [Description("RightAlt")]
        RAlt,
        [Description("Pause")]
        Pause,
        [Description("Home")]
        Home,
        [Description("Up")]
        Up,
        [Description("PageUp")]
        PageUp,
        [Description("Left")]
        Left,
        [Description("Right")]
        Right,
        [Description("End")]
        End,
        [Description("Down")]
        Down,
        [Description("Insert")]
        Insert,
        [Description("Delete")]
        Delete,
        [Description("LeftWindows")]
        LWindows,
        [Description("RightWindows")]
        RWindows,
        [Description("Menu")]
        Menu
    }
}
