//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfExecutor.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfExecutor.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дополнительна информация.
        /// </summary>
        internal static string AboutWindow_AdditionalInfo {
            get {
                return ResourceManager.GetString("AboutWindow_AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сторонние Пакеты:
        ///	Newtonsoft.Json (MIT) / https://github.com/JamesNK/Newtonsoft.Json
        ///Сторонние Значки:
        ///	https://icons8.com
        ///Сторонние Шрифты:
        ///	Roboto (Apache License 2.0) / https://github.com/google/roboto.
        /// </summary>
        internal static string AboutWindow_packages {
            get {
                return ResourceManager.GetString("AboutWindow_packages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать действие.
        /// </summary>
        internal static string AddActionWindow {
            get {
                return ResourceManager.GetString("AddActionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип действия.
        /// </summary>
        internal static string AddActionWindow_ActionType {
            get {
                return ResourceManager.GetString("AddActionWindow_ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление/Редактирование.
        /// </summary>
        internal static string AddBotActionWindow {
            get {
                return ResourceManager.GetString("AddBotActionWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВНИМАНИЕ:
        ///Стоит иметь в виду, что если действие не имеет собственного возвращаемого результата, то действие вернёт (пробросит) результат предыдущего действия..
        /// </summary>
        internal static string AddWarning {
            get {
                return ResourceManager.GetString("AddWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите выйти из программы?.
        /// </summary>
        internal static string CloseMessage {
            get {
                return ResourceManager.GetString("CloseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string CloseMessageTitle {
            get {
                return ResourceManager.GetString("CloseMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактор условий.
        /// </summary>
        internal static string ConditionalEditorWindow {
            get {
                return ResourceManager.GetString("ConditionalEditorWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия конфигурации.
        /// </summary>
        internal static string ConfigVersion {
            get {
                return ResourceManager.GetString("ConfigVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Продолжить.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ядро.
        /// </summary>
        internal static string Core {
            get {
                return ResourceManager.GetString("Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры ядра.
        /// </summary>
        internal static string CoreSettingWindow {
            get {
                return ResourceManager.GetString("CoreSettingWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки ядра.
        /// </summary>
        internal static string CoreSettingWindow_CoreSettings {
            get {
                return ResourceManager.GetString("CoreSettingWindow_CoreSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Использовать базовое ядро.
        /// </summary>
        internal static string CoreSettingWindow_DefaultCore {
            get {
                return ResourceManager.GetString("CoreSettingWindow_DefaultCore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод ввода с клавы.
        /// </summary>
        internal static string CoreSettingWindow_KeyBoardInputMethod {
            get {
                return ResourceManager.GetString("CoreSettingWindow_KeyBoardInputMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загружать плагины.
        /// </summary>
        internal static string CoreSettingWindow_LoadPlugin {
            get {
                return ResourceManager.GetString("CoreSettingWindow_LoadPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Настройки каналов уведомлений.
        /// </summary>
        internal static string CoreSettingWindow_NotificationChannelSettings {
            get {
                return ResourceManager.GetString("CoreSettingWindow_NotificationChannelSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приоритеты.
        /// </summary>
        internal static string CoreSettingWindow_Priority {
            get {
                return ResourceManager.GetString("CoreSettingWindow_Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp хост.
        /// </summary>
        internal static string CoreSettingWindow_SmtpHost {
            get {
                return ResourceManager.GetString("CoreSettingWindow_SmtpHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp логин.
        /// </summary>
        internal static string CoreSettingWindow_SmtpLogin {
            get {
                return ResourceManager.GetString("CoreSettingWindow_SmtpLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp пароль.
        /// </summary>
        internal static string CoreSettingWindow_SmtpPassword {
            get {
                return ResourceManager.GetString("CoreSettingWindow_SmtpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smtp порт.
        /// </summary>
        internal static string CoreSettingWindow_SmtpPort {
            get {
                return ResourceManager.GetString("CoreSettingWindow_SmtpPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите удалить элемент?.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить?.
        /// </summary>
        internal static string DeleteMessageTitle {
            get {
                return ResourceManager.GetString("DeleteMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на указывает что бот должен ожидать появления окна с указанным заголовком, только после его появления будет продолжено исполнение инструкций.
        /// </summary>
        internal static string Description_ExpectWindow {
            get {
                return ResourceManager.GetString("Description_ExpectWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получает текущую позицию курсора, результат может быть переданн следующему вызову, или запулин в стек..
        /// </summary>
        internal static string Description_GetMousePos {
            get {
                return ResourceManager.GetString("Description_GetMousePos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данное действие получает информацию об объекте находящемся в указанной позиции. 
        ///К такой информации относится:
        ///Type - Тип объекта
        ///Titile - Наименование
        ///Pos - Позиция
        ///Size - Размер
        ///И дескриптор объекта
        ///Результат исполнения может быть передан следующему вызову..
        /// </summary>
        internal static string Description_GetObject {
            get {
                return ResourceManager.GetString("Description_GetObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция создаёт скриншот экрана. Данное действие может возвращать чёрный экран в DX приложениях..
        /// </summary>
        internal static string Description_GetScreenshot {
            get {
                return ResourceManager.GetString("Description_GetScreenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор безусловного перехода к определённой точке программы, обозначенной  меткой.
        ///Область видимости оператора ограниченна текущим уровнем вложенности..
        /// </summary>
        internal static string Description_GOTO {
            get {
                return ResourceManager.GetString("Description_GOTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор условного ветвления, В РАЗРАБОТКЕ.
        /// </summary>
        internal static string Description_If {
            get {
                return ResourceManager.GetString("Description_If", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие нажатия одной или нескольких клавиш последовательно..
        /// </summary>
        internal static string Description_KeyBoard {
            get {
                return ResourceManager.GetString("Description_KeyBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие нажатия одновременно нескольких клавиш на клавиатуре.
        ///Иначе говоря нажатие сочитания клавиш..
        /// </summary>
        internal static string Description_KeyBoardKeys {
            get {
                return ResourceManager.GetString("Description_KeyBoardKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метка, указывает целевую точку для перехода в программе, например: goto метка.
        ///Действие оператора GOTO состоит в том, что после его исполнения следующими будут исполняться операторы программы, идущие в тексте непосредственно после метки..
        /// </summary>
        internal static string Description_Label {
            get {
                return ResourceManager.GetString("Description_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оператор цикла, выполняет список указанных действий, указанное колличество раз.
        ///Внимание! При использовании стека в цикле следите за тем что бы он не переполнялся!.
        /// </summary>
        internal static string Description_Loop {
            get {
                return ResourceManager.GetString("Description_Loop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нечего не делает, дебаговый объект..
        /// </summary>
        internal static string Description_Mock {
            get {
                return ResourceManager.GetString("Description_Mock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Щелчёк левой кнопки мыши.
        /// </summary>
        internal static string Description_MouseLClick {
            get {
                return ResourceManager.GetString("Description_MouseLClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие зажатия левой кнопки мыши.
        ///Мышка не будет отжата до тех пор пока не будет вызвано соответсвующее событие.
        ///Это может быть полезно если например надо что то перетащить..
        /// </summary>
        internal static string Description_MouseLPress {
            get {
                return ResourceManager.GetString("Description_MouseLPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие отжатия левой кнопки мышки..
        /// </summary>
        internal static string Description_MouseLUp {
            get {
                return ResourceManager.GetString("Description_MouseLUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие перемещения мышки в указанную позицию.
        ///Мышка может быть перемещена как и на указанное смещение, так и к конкретному объекту, который является результатом предыдущего вызова..
        /// </summary>
        internal static string Description_MouseMove {
            get {
                return ResourceManager.GetString("Description_MouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнить щелчёк правой кнопкой мышки.
        /// </summary>
        internal static string Description_MouseRClick {
            get {
                return ResourceManager.GetString("Description_MouseRClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие зажатия правой кнопки мыши.
        /// </summary>
        internal static string Description_MouseRPress {
            get {
                return ResourceManager.GetString("Description_MouseRPress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действие отжатия правой кнопки мыши.
        /// </summary>
        internal static string Description_MouseRUp {
            get {
                return ResourceManager.GetString("Description_MouseRUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поставить курсор в указанную позицию. Позиция не может принимать отрицательные значения по оси координат. Однако может рассчитывать относительно какого либо объекта, например окна, явлющегося результатом вызова функции ExpectWindow.
        /// </summary>
        internal static string Description_MouseSetPos {
            get {
                return ResourceManager.GetString("Description_MouseSetPos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание действий к исполнению для плагина.
        ///В данный момент находится в разработке..
        /// </summary>
        internal static string Description_PluginAct {
            get {
                return ResourceManager.GetString("Description_PluginAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вызывает плагин и передаёт ему список указанных действий. .
        /// </summary>
        internal static string Description_PluginInvoke {
            get {
                return ResourceManager.GetString("Description_PluginInvoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Функция инициирует отправку заданного сообщения на указанный канал связи.
        ///На текущий момент поддерживается только емайл..
        /// </summary>
        internal static string Description_SendMessage {
            get {
                return ResourceManager.GetString("Description_SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия сна бота. То есть пока не закончится указанное время, бот не перейдёт к следующей комманде..
        /// </summary>
        internal static string Description_Sleep {
            get {
                return ResourceManager.GetString("Description_Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Представляет собой список результатов выполнений, организованных по принципу LIFO..
        /// </summary>
        internal static string Description_Stack {
            get {
                return ResourceManager.GetString("Description_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Скрыть детали.
        /// </summary>
        internal static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на English.
        /// </summary>
        internal static string Language_eng {
            get {
                return ResourceManager.GetString("Language_eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Русский.
        /// </summary>
        internal static string Language_rus {
            get {
                return ResourceManager.GetString("Language_rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Текущий документ не пуст. Создание нового документа приведёт к удалению всех не сохранёных изменений. Вы хотите продолжить?.
        /// </summary>
        internal static string NewDocMessage {
            get {
                return ResourceManager.GetString("NewDocMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый документ.
        /// </summary>
        internal static string NewDocMessageTitle {
            get {
                return ResourceManager.GetString("NewDocMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не поддерживается.
        /// </summary>
        internal static string NotSupported {
            get {
                return ResourceManager.GetString("NotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для данного действия множественные под действия не поддерживаются..
        /// </summary>
        internal static string NotSupportedMessage {
            get {
                return ResourceManager.GetString("NotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не поддерживается.
        /// </summary>
        internal static string NotSupportedMessageTitle {
            get {
                return ResourceManager.GetString("NotSupportedMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы действительно хотите сохранить изменения?.
        /// </summary>
        internal static string SaveCommandMessage {
            get {
                return ResourceManager.GetString("SaveCommandMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string SaveCommandMessageTitle {
            get {
                return ResourceManager.GetString("SaveCommandMessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла.
        /// </summary>
        internal static string SaveFileParamUserControl_FileName {
            get {
                return ResourceManager.GetString("SaveFileParamUserControl_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        internal static string SaveFileParamUserControl_Path {
            get {
                return ResourceManager.GetString("SaveFileParamUserControl_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить файл.
        /// </summary>
        internal static string SaveFileParamUserControl_SaveFile {
            get {
                return ResourceManager.GetString("SaveFileParamUserControl_SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип файла.
        /// </summary>
        internal static string SaveFileParamUserControl_Type {
            get {
                return ResourceManager.GetString("SaveFileParamUserControl_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Показать детали.
        /// </summary>
        internal static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Прервать!.
        /// </summary>
        internal static string Text_Abort {
            get {
                return ResourceManager.GetString("Text_Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе.
        /// </summary>
        internal static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Действия.
        /// </summary>
        internal static string Text_Actions {
            get {
                return ResourceManager.GetString("Text_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        internal static string Text_Add {
            get {
                return ResourceManager.GetString("Text_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        internal static string Text_Cancel {
            get {
                return ResourceManager.GetString("Text_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Закрыть.
        /// </summary>
        internal static string Text_Close {
            get {
                return ResourceManager.GetString("Text_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить.
        /// </summary>
        internal static string Text_Delete {
            get {
                return ResourceManager.GetString("Text_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        internal static string Text_Edit {
            get {
                return ResourceManager.GetString("Text_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Список ошибок.
        /// </summary>
        internal static string Text_ErrorList {
            get {
                return ResourceManager.GetString("Text_ErrorList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выход.
        /// </summary>
        internal static string Text_Exit {
            get {
                return ResourceManager.GetString("Text_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отключено.
        /// </summary>
        internal static string Text_False {
            get {
                return ResourceManager.GetString("Text_False", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Высота: .
        /// </summary>
        internal static string Text_Height {
            get {
                return ResourceManager.GetString("Text_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справка.
        /// </summary>
        internal static string Text_Help {
            get {
                return ResourceManager.GetString("Text_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Json.
        /// </summary>
        internal static string Text_Json {
            get {
                return ResourceManager.GetString("Text_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логи.
        /// </summary>
        internal static string Text_Logs {
            get {
                return ResourceManager.GetString("Text_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новый.
        /// </summary>
        internal static string Text_New {
            get {
                return ResourceManager.GetString("Text_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на По умолчанию.
        /// </summary>
        internal static string Text_Null {
            get {
                return ResourceManager.GetString("Text_Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть.
        /// </summary>
        internal static string Text_Open {
            get {
                return ResourceManager.GetString("Text_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь.
        /// </summary>
        internal static string Text_Path {
            get {
                return ResourceManager.GetString("Text_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Старт.
        /// </summary>
        internal static string Text_Run {
            get {
                return ResourceManager.GetString("Text_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        internal static string Text_Save {
            get {
                return ResourceManager.GetString("Text_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить как.
        /// </summary>
        internal static string Text_SaveAs {
            get {
                return ResourceManager.GetString("Text_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Параметры ядра.
        /// </summary>
        internal static string Text_Settings {
            get {
                return ResourceManager.GetString("Text_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Включено.
        /// </summary>
        internal static string Text_True {
            get {
                return ResourceManager.GetString("Text_True", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ширина: .
        /// </summary>
        internal static string Text_Width {
            get {
                return ResourceManager.GetString("Text_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на О программе: Консоль управления автоматизатором действий.
        /// </summary>
        internal static string Title_AboutWin {
            get {
                return ResourceManager.GetString("Title_AboutWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Консоль управления для бота.
        /// </summary>
        internal static string Title_MainWin {
            get {
                return ResourceManager.GetString("Title_MainWin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Версия:.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
